name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: PyPI Deployment
        uses: casperdcl/deploy-pypi@v2.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          build: true          # <-- REQUIRED for building
          dist_dir: dist       # matches where build outputs go

